### ISSUE TITLE
store.get_menu raised an exception

### ISSUE THREAD

**Issue by anask1234** [gamagori/pizzapi#119]
this is my code
```
from pizzapi import *




print("Order dominos")
fname = input("What is your first name? : ")
lname = input('What is your last name? : ')
email = input("What is your email? : ")
phonenum = input("What is your phone number? : ")
customer = Customer(fname, lname, email, phonenum)


stradd = input("What is your street address? : ")
city = input("What is your city? : ")
state = input("What is your state? : ")
zip = input("What is your zip code? : ")
address = Address(stradd, city, state, zip)
store = address.closest_store()
print(f"{store} is your closest store. Would you still like to order? ")
yn = input("Yes or no? [y,n]")
if yn == "y":
  print("Ok hold on")
  menu = store.get_menu()
  menu.search(Name='Pizza')
  print(f"{menu}")
  print("Please respond with your product code")
  code = input("Code ? : ")
  order = Order(store, customer, address)
  order.add_item(code) 
  cnum = input("Card number? ")
  exp = input("Card expiration date? ")
  cvv = input("Card security code? ")
  card = PaymentObject(cnum, exp, cvv, zip)
  order.pay_with(card)
  
  
else:
  print("Ok i wont order")

```
and this is the error

```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    menu = store.get_menu()
  File "/home/runner/dominos-bot/venv/lib/python3.8/site-packages/pizzapi/store.py", line 24, in get_menu
    menu = Menu(response, self.country)
  File "/home/runner/dominos-bot/venv/lib/python3.8/site-packages/pizzapi/menu.py", line 50, in __init__
    self.root_categories[key] = self.build_categories(value)
  File "/home/runner/dominos-bot/venv/lib/python3.8/site-packages/pizzapi/menu.py", line 62, in build_categories
    new_subcategory = self.build_categories(subcategory, category)
  File "/home/runner/dominos-bot/venv/lib/python3.8/site-packages/pizzapi/menu.py", line 66, in build_categories
    raise Exception('PRODUCT NOT FOUND: %s %s' % (product_code, category.code))
Exception: PRODUCT NOT FOUND: 5156 CouponPizza
```

**Comment by anask1234** [comment]
solved it
