### ISSUE TITLE
Order class broken

### ISSUE THREAD

**Issue by voron434** [gamagori/pizzapi#59]
I tried running your code example from README, but there is an  inconsistent use of tabs and spaces in pizzapi/order.py:

Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux

```
>>> from pizzapi import Customer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ilya/Desktop/subl/venv/lib/python3.6/site-packages/pizzapi/__init__.py", line 5, in <module>
    from .order import Order
  File "/home/ilya/Desktop/subl/venv/lib/python3.6/site-packages/pizzapi/order.py", line 130
    return response
                  ^
TabError: inconsistent use of tabs and spaces in indentation
```
```
>>> from pizzapi import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ilya/Desktop/subl/venv/lib/python3.6/site-packages/pizzapi/__init__.py", line 5, in <module>
    from .order import Order
  File "/home/ilya/Desktop/subl/venv/lib/python3.6/site-packages/pizzapi/order.py", line 130
    return response
                  ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by Pokemaniac00** [comment]
Deleting the empty line below seemed to fix the problem for me.
